name: "Core-Specs-1.5base"

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; [MooTools](http://mootools.net)"

authors: "[MooTools Development Team](http://mootools.net/developers)"

sources:
  - "Core/Core.js"
  - "Fx/Fx.js"
