name: "Core-Specs-1.4base"

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; [MooTools](http://mootools.net)"

authors: "[MooTools Development Team](http://mootools.net/developers)"

sources:
  - "Types/Array.js"
  - "Types/Function-nocompat.js"
